// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9HJ9SmJ2iV-RJypM9vJYNR_djw6570Fg',
    appId: '1:117247412681:web:5db117192d87bd3fff0018',
    messagingSenderId: '117247412681',
    projectId: 'login-chan',
    authDomain: 'login-chan.firebaseapp.com',
    storageBucket: 'login-chan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJnjRLzr2PI-rU_EiYhWnGzd_GUP5wj8',
    appId: '1:117247412681:android:851aad20be56fd6eff0018',
    messagingSenderId: '117247412681',
    projectId: 'login-chan',
    storageBucket: 'login-chan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjM2s6XoEvhG2m4UTZBCTHNgbuuLAVvXE',
    appId: '1:117247412681:ios:f097a3e5fccec3f2ff0018',
    messagingSenderId: '117247412681',
    projectId: 'login-chan',
    storageBucket: 'login-chan.appspot.com',
    androidClientId: '117247412681-h1vv0vfulg1vbhqhj6cb9aonhbrm3aha.apps.googleusercontent.com',
    iosClientId: '117247412681-3qc423f6vuq0aea3rc9caid937g14cvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjM2s6XoEvhG2m4UTZBCTHNgbuuLAVvXE',
    appId: '1:117247412681:ios:f097a3e5fccec3f2ff0018',
    messagingSenderId: '117247412681',
    projectId: 'login-chan',
    storageBucket: 'login-chan.appspot.com',
    androidClientId: '117247412681-h1vv0vfulg1vbhqhj6cb9aonhbrm3aha.apps.googleusercontent.com',
    iosClientId: '117247412681-3qc423f6vuq0aea3rc9caid937g14cvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
